// <auto-generated />
using System;
using AlpineHub.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AlpineHub.Data.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20241127151102_SeedDb")]
    partial class SeedDb
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("AlpineHub.Data.Models.ApplicationUser", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<DateTime?>("Birthdate")
                        .HasColumnType("datetime2")
                        .HasComment("Birthdate of user");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasComment("First name of user");

                    b.Property<string>("LastName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasComment("Last name of user");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("AlpineHub.Data.Models.Lift", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("AverageAscendTime")
                        .HasColumnType("int")
                        .HasComment("Average ascend time in minutes");

                    b.Property<int>("CapacityPerHour")
                        .HasColumnType("int")
                        .HasComment("Max number of people per hour");

                    b.Property<TimeOnly>("ClosingHour")
                        .HasColumnType("time")
                        .HasComment("Closing hour of lift");

                    b.Property<bool>("IsOpen")
                        .HasColumnType("bit")
                        .HasComment("Lift status flag");

                    b.Property<int>("Length")
                        .HasColumnType("int")
                        .HasComment("Length of ski lift in meters");

                    b.Property<Guid>("LiftTypeId")
                        .HasColumnType("uniqueidentifier")
                        .HasComment("Foreign key for lift type relation");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)")
                        .HasComment("Name of ski lift");

                    b.Property<int>("NumberOfSeats")
                        .HasColumnType("int")
                        .HasComment("Number of seats of lift");

                    b.Property<TimeOnly>("OpenningHour")
                        .HasColumnType("time")
                        .HasComment("Openning hour of lift");

                    b.Property<int>("VerticalAscend")
                        .HasColumnType("int")
                        .HasComment("Vertical ascend of lift in meters");

                    b.HasKey("Id");

                    b.HasIndex("LiftTypeId");

                    b.ToTable("Lifts");

                    b.HasData(
                        new
                        {
                            Id = new Guid("b8e3e16a-df12-4a92-8fd3-0d28482c6ccd"),
                            AverageAscendTime = 25,
                            CapacityPerHour = 2000,
                            ClosingHour = new TimeOnly(16, 30, 0),
                            IsOpen = true,
                            Length = 2500,
                            LiftTypeId = new Guid("eb42a879-b6b2-4c50-b8d4-4336e97e67a6"),
                            Name = "Mountain Gondola",
                            NumberOfSeats = 8,
                            OpenningHour = new TimeOnly(8, 30, 0),
                            VerticalAscend = 400
                        },
                        new
                        {
                            Id = new Guid("74dfc2a7-0ed4-42ca-a0e1-99070021ab0c"),
                            AverageAscendTime = 10,
                            CapacityPerHour = 1300,
                            ClosingHour = new TimeOnly(16, 30, 0),
                            IsOpen = true,
                            Length = 1300,
                            LiftTypeId = new Guid("458000dd-f5b8-455c-b0be-71db4ec53f1f"),
                            Name = "Spring rider",
                            NumberOfSeats = 6,
                            OpenningHour = new TimeOnly(8, 30, 0),
                            VerticalAscend = 300
                        },
                        new
                        {
                            Id = new Guid("5279b012-1187-4ef8-bad2-440d3c2dca45"),
                            AverageAscendTime = 12,
                            CapacityPerHour = 1200,
                            ClosingHour = new TimeOnly(16, 0, 0),
                            IsOpen = false,
                            Length = 1500,
                            LiftTypeId = new Guid("458000dd-f5b8-455c-b0be-71db4ec53f1f"),
                            Name = "Lakavator",
                            NumberOfSeats = 8,
                            OpenningHour = new TimeOnly(8, 45, 0),
                            VerticalAscend = 400
                        });
                });

            modelBuilder.Entity("AlpineHub.Data.Models.LiftType", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasComment("Primary key of table");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasComment("Name of lift type");

                    b.HasKey("Id");

                    b.ToTable("LiftTypes");

                    b.HasData(
                        new
                        {
                            Id = new Guid("e400e024-3f0f-4ad6-84b5-b6392c1a7cfd"),
                            Name = "Gondola"
                        },
                        new
                        {
                            Id = new Guid("6c670604-4c9a-4066-b0b1-5974955ef7f9"),
                            Name = "Chairlift"
                        });
                });

            modelBuilder.Entity("AlpineHub.Data.Models.PassAgeGroup", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasComment("Primary key of table");

                    b.Property<int>("MaxAge")
                        .HasColumnType("int")
                        .HasComment("Max age of client");

                    b.Property<int>("MinAge")
                        .HasColumnType("int")
                        .HasComment("Min age of client");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)")
                        .HasComment("Name of age group");

                    b.HasKey("Id");

                    b.ToTable("PassAgeGroups");
                });

            modelBuilder.Entity("AlpineHub.Data.Models.PassPeriod", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasComment("Primary key of table PassPeriods");

                    b.Property<int>("DaysCount")
                        .HasColumnType("int")
                        .HasComment("Number of days for pass validity");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasComment("Name of pass period");

                    b.Property<int>("ValidFromHour")
                        .HasColumnType("int")
                        .HasComment("Starting hour of pass period");

                    b.Property<int>("ValidToHour")
                        .HasColumnType("int")
                        .HasComment("Ending hour of pass period");

                    b.HasKey("Id");

                    b.ToTable("PassPeriods");
                });

            modelBuilder.Entity("AlpineHub.Data.Models.PassType", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasComment("Primary key of table");

                    b.Property<decimal>("DiscountPercentage")
                        .HasColumnType("decimal(18,2)")
                        .HasComment("Discount of current pass type");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)")
                        .HasComment("Name of pass type");

                    b.HasKey("Id");

                    b.ToTable("PassTypes");
                });

            modelBuilder.Entity("AlpineHub.Data.Models.Passes", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasComment("Primary key of table");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit")
                        .HasComment("Flag for soft deletion");

                    b.Property<Guid>("PassAgeGroupId")
                        .HasColumnType("uniqueidentifier")
                        .HasComment("Foreign key for pass age group");

                    b.Property<Guid>("PassPeriodId")
                        .HasColumnType("uniqueidentifier")
                        .HasComment("Foreign key for pass period");

                    b.Property<Guid>("PassTypeId")
                        .HasColumnType("uniqueidentifier")
                        .HasComment("Foreign key for pass type");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)")
                        .HasComment("Pass price. Pass type discount is automatically deduced");

                    b.Property<DateTime>("ValidFromDate")
                        .HasColumnType("datetime2")
                        .HasComment("Start of validity period");

                    b.Property<DateTime>("ValidToDate")
                        .HasColumnType("datetime2")
                        .HasComment("End of validity period");

                    b.HasKey("Id");

                    b.HasIndex("PassAgeGroupId");

                    b.HasIndex("PassPeriodId");

                    b.HasIndex("PassTypeId");

                    b.ToTable("Passes");
                });

            modelBuilder.Entity("AlpineHub.Data.Models.Slope", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Difficulty")
                        .HasColumnType("int")
                        .HasComment("Slope difficulty enum");

                    b.Property<bool>("IsOpen")
                        .HasColumnType("bit")
                        .HasComment("Flag indicating if slope is open");

                    b.Property<int>("Length")
                        .HasColumnType("int")
                        .HasComment("Length of the slope in meters");

                    b.Property<int>("LowerPointAltitude")
                        .HasColumnType("int")
                        .HasComment("Elevation at lowest point of the slope");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasComment("Name of the slope");

                    b.Property<int>("SlopeCondition")
                        .HasColumnType("int")
                        .HasComment("Slope condition enum");

                    b.Property<int>("UpperPointAltitude")
                        .HasColumnType("int")
                        .HasComment("Elevation at upmost point of the slope");

                    b.HasKey("Id");

                    b.ToTable("Slopes");

                    b.HasData(
                        new
                        {
                            Id = new Guid("c99d8323-b7ae-48b6-b299-739ffc547e1b"),
                            Difficulty = 4,
                            IsOpen = true,
                            Length = 2000,
                            LowerPointAltitude = 1300,
                            Name = "Wolf ride",
                            SlopeCondition = 0,
                            UpperPointAltitude = 2200
                        },
                        new
                        {
                            Id = new Guid("870a9ac9-153b-4f33-94d7-c9c70c455393"),
                            Difficulty = 2,
                            IsOpen = true,
                            Length = 800,
                            LowerPointAltitude = 1800,
                            Name = "Rabbit's hole",
                            SlopeCondition = 0,
                            UpperPointAltitude = 2000
                        },
                        new
                        {
                            Id = new Guid("b307d0ac-a44a-4e9f-bb00-8cabad6d0afb"),
                            Difficulty = 0,
                            IsOpen = true,
                            Length = 300,
                            LowerPointAltitude = 1350,
                            Name = "Lerner's paradise",
                            SlopeCondition = 1,
                            UpperPointAltitude = 1450
                        });
                });

            modelBuilder.Entity("AlpineHub.Data.Models.SlopeLift", b =>
                {
                    b.Property<Guid>("SlopeId")
                        .HasColumnType("uniqueidentifier")
                        .HasComment("Id of slope");

                    b.Property<Guid>("LiftId")
                        .HasColumnType("uniqueidentifier")
                        .HasComment("Id of lift");

                    b.HasKey("SlopeId", "LiftId");

                    b.HasIndex("LiftId");

                    b.ToTable("SlopesLifts");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole<System.Guid>", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("AlpineHub.Data.Models.Lift", b =>
                {
                    b.HasOne("AlpineHub.Data.Models.LiftType", "LiftType")
                        .WithMany("Lifts")
                        .HasForeignKey("LiftTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("LiftType");
                });

            modelBuilder.Entity("AlpineHub.Data.Models.Passes", b =>
                {
                    b.HasOne("AlpineHub.Data.Models.PassAgeGroup", "PassAgeGroup")
                        .WithMany()
                        .HasForeignKey("PassAgeGroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AlpineHub.Data.Models.PassPeriod", "PassPeriod")
                        .WithMany()
                        .HasForeignKey("PassPeriodId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AlpineHub.Data.Models.PassType", "PassType")
                        .WithMany()
                        .HasForeignKey("PassTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PassAgeGroup");

                    b.Navigation("PassPeriod");

                    b.Navigation("PassType");
                });

            modelBuilder.Entity("AlpineHub.Data.Models.SlopeLift", b =>
                {
                    b.HasOne("AlpineHub.Data.Models.Lift", "Lift")
                        .WithMany()
                        .HasForeignKey("LiftId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AlpineHub.Data.Models.Slope", "Slope")
                        .WithMany()
                        .HasForeignKey("SlopeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Lift");

                    b.Navigation("Slope");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<System.Guid>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.HasOne("AlpineHub.Data.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.HasOne("AlpineHub.Data.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<System.Guid>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AlpineHub.Data.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.HasOne("AlpineHub.Data.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("AlpineHub.Data.Models.LiftType", b =>
                {
                    b.Navigation("Lifts");
                });
#pragma warning restore 612, 618
        }
    }
}
