// <auto-generated />
using System;
using AlpineHub.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AlpineHub.Data.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20241211101812_SeedData")]
    partial class SeedData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("AlpineHub.Data.Models.ApplicationUser", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<DateTime?>("Birthdate")
                        .HasColumnType("datetime2")
                        .HasComment("Birthdate of user");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("FirstName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasComment("First name of user");

                    b.Property<string>("LastName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasComment("Last name of user");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("AlpineHub.Data.Models.CartItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasComment("Primary key of table");

                    b.Property<Guid>("CartId")
                        .HasColumnType("uniqueidentifier")
                        .HasComment("Foreign key for cart");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<Guid>("PassId")
                        .HasColumnType("uniqueidentifier")
                        .HasComment("Foreign key for pass");

                    b.Property<int>("Quantity")
                        .HasColumnType("int")
                        .HasComment("Number of passes");

                    b.Property<decimal>("TotalPrice")
                        .HasColumnType("decimal(18,2)")
                        .HasComment("Total price of passes");

                    b.HasKey("Id");

                    b.HasIndex("CartId");

                    b.HasIndex("PassId");

                    b.ToTable("CartItems");
                });

            modelBuilder.Entity("AlpineHub.Data.Models.Lift", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("AverageAscendTime")
                        .HasColumnType("int")
                        .HasComment("Average ascend time in minutes");

                    b.Property<int>("CapacityPerHour")
                        .HasColumnType("int")
                        .HasComment("Max number of people per hour");

                    b.Property<TimeOnly>("ClosingTime")
                        .HasColumnType("time")
                        .HasComment("Closing hour of lift");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit")
                        .HasComment("Soft delete flag");

                    b.Property<bool>("IsOpen")
                        .HasColumnType("bit")
                        .HasComment("Lift status flag");

                    b.Property<int>("Length")
                        .HasColumnType("int")
                        .HasComment("Length of ski lift in meters");

                    b.Property<Guid>("LiftTypeId")
                        .HasColumnType("uniqueidentifier")
                        .HasComment("Foreign key for lift type relation");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)")
                        .HasComment("Name of ski lift");

                    b.Property<int>("NumberOfSeats")
                        .HasColumnType("int")
                        .HasComment("Number of seats of lift");

                    b.Property<TimeOnly>("OpenningTime")
                        .HasColumnType("time")
                        .HasComment("Openning hour of lift");

                    b.Property<int>("VerticalAscend")
                        .HasColumnType("int")
                        .HasComment("Vertical ascend of lift in meters");

                    b.HasKey("Id");

                    b.HasIndex("LiftTypeId");

                    b.ToTable("Lifts");

                    b.HasData(
                        new
                        {
                            Id = new Guid("026a5b7a-3c58-4597-b6ac-97a2bccbc2e2"),
                            AverageAscendTime = 25,
                            CapacityPerHour = 2000,
                            ClosingTime = new TimeOnly(16, 30, 0),
                            IsDeleted = false,
                            IsOpen = true,
                            Length = 2500,
                            LiftTypeId = new Guid("bcfe0a51-7088-451a-a02d-0c46c9a9ed6b"),
                            Name = "Mountain Gondola",
                            NumberOfSeats = 8,
                            OpenningTime = new TimeOnly(8, 30, 0),
                            VerticalAscend = 400
                        },
                        new
                        {
                            Id = new Guid("a80408aa-72fc-4b44-97cd-67274837c089"),
                            AverageAscendTime = 10,
                            CapacityPerHour = 1300,
                            ClosingTime = new TimeOnly(16, 30, 0),
                            IsDeleted = false,
                            IsOpen = true,
                            Length = 1300,
                            LiftTypeId = new Guid("dde8a2c0-a446-48b1-9da9-f3cb095b1662"),
                            Name = "Spring rider",
                            NumberOfSeats = 6,
                            OpenningTime = new TimeOnly(8, 30, 0),
                            VerticalAscend = 300
                        },
                        new
                        {
                            Id = new Guid("b22afe8a-f6d8-4bab-ae8f-de602d760724"),
                            AverageAscendTime = 12,
                            CapacityPerHour = 1200,
                            ClosingTime = new TimeOnly(16, 0, 0),
                            IsDeleted = false,
                            IsOpen = false,
                            Length = 1500,
                            LiftTypeId = new Guid("dde8a2c0-a446-48b1-9da9-f3cb095b1662"),
                            Name = "Lakavator",
                            NumberOfSeats = 8,
                            OpenningTime = new TimeOnly(8, 45, 0),
                            VerticalAscend = 400
                        });
                });

            modelBuilder.Entity("AlpineHub.Data.Models.LiftType", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasComment("Primary key of table");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasComment("Name of lift type");

                    b.HasKey("Id");

                    b.ToTable("LiftTypes");

                    b.HasData(
                        new
                        {
                            Id = new Guid("bcfe0a51-7088-451a-a02d-0c46c9a9ed6b"),
                            Name = "Gondola"
                        },
                        new
                        {
                            Id = new Guid("dde8a2c0-a446-48b1-9da9-f3cb095b1662"),
                            Name = "Chairlift"
                        });
                });

            modelBuilder.Entity("AlpineHub.Data.Models.Pass", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasComment("Primary key of table");

                    b.Property<string>("Description")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)")
                        .HasComment("Description of pass");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit")
                        .HasComment("Flag for soft deletion");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)")
                        .HasComment("Name of pass");

                    b.Property<Guid>("PassAgeGroupId")
                        .HasColumnType("uniqueidentifier")
                        .HasComment("Foreign key for pass age group");

                    b.Property<Guid>("PassPeriodId")
                        .HasColumnType("uniqueidentifier")
                        .HasComment("Foreign key for pass period");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)")
                        .HasComment("Pass price. Pass type discount is automatically deduced");

                    b.HasKey("Id");

                    b.HasIndex("PassAgeGroupId");

                    b.HasIndex("PassPeriodId");

                    b.ToTable("Passes");

                    b.HasData(
                        new
                        {
                            Id = new Guid("0cff3e71-c04d-4e53-bcc5-423b6ddf3eb6"),
                            IsDeleted = false,
                            Name = "All day adult pass",
                            PassAgeGroupId = new Guid("a1371258-86d8-4ec2-9fbf-9b03a31cd548"),
                            PassPeriodId = new Guid("a91d8261-2dd1-4631-a379-ce4cff155371"),
                            Price = 50m
                        },
                        new
                        {
                            Id = new Guid("1fd6ce7d-3a4e-4da3-aaed-44c662977e38"),
                            IsDeleted = false,
                            Name = "All day student pass",
                            PassAgeGroupId = new Guid("cae47722-1b8a-4578-b1c8-1f8b0412d7f1"),
                            PassPeriodId = new Guid("a91d8261-2dd1-4631-a379-ce4cff155371"),
                            Price = 40m
                        },
                        new
                        {
                            Id = new Guid("c1ae2c08-937a-4722-9bbf-cbc3413473eb"),
                            IsDeleted = false,
                            Name = "All day child pass",
                            PassAgeGroupId = new Guid("3d8819ca-f1cf-48cd-c851-08dd19791faa"),
                            PassPeriodId = new Guid("a91d8261-2dd1-4631-a379-ce4cff155371"),
                            Price = 30m
                        },
                        new
                        {
                            Id = new Guid("9fe2c683-9598-4fbb-b335-392ac0da0e13"),
                            IsDeleted = false,
                            Name = "Morning adult pass",
                            PassAgeGroupId = new Guid("a1371258-86d8-4ec2-9fbf-9b03a31cd548"),
                            PassPeriodId = new Guid("235024b0-64b9-4e2e-a0ee-48d0a2750953"),
                            Price = 30m
                        },
                        new
                        {
                            Id = new Guid("399aa10a-5c7e-4140-98a5-1e9ce3d75b78"),
                            IsDeleted = false,
                            Name = "Morning child pass",
                            PassAgeGroupId = new Guid("3d8819ca-f1cf-48cd-c851-08dd19791faa"),
                            PassPeriodId = new Guid("235024b0-64b9-4e2e-a0ee-48d0a2750953"),
                            Price = 20m
                        },
                        new
                        {
                            Id = new Guid("74c845f9-6a8d-47b4-a7ea-fd5ec8466af8"),
                            IsDeleted = false,
                            Name = "Morning student pass",
                            PassAgeGroupId = new Guid("cae47722-1b8a-4578-b1c8-1f8b0412d7f1"),
                            PassPeriodId = new Guid("235024b0-64b9-4e2e-a0ee-48d0a2750953"),
                            Price = 25m
                        },
                        new
                        {
                            Id = new Guid("2a0c01fa-7784-44d2-889d-a6dc4c67dec9"),
                            IsDeleted = false,
                            Name = "Afternoon child pass",
                            PassAgeGroupId = new Guid("3d8819ca-f1cf-48cd-c851-08dd19791faa"),
                            PassPeriodId = new Guid("727c219a-0e3a-4eeb-9215-8602cbd62372"),
                            Price = 20m
                        },
                        new
                        {
                            Id = new Guid("129b095a-13c8-4acb-86b2-1eb9445693eb"),
                            IsDeleted = false,
                            Name = "Afternoon adult pass",
                            PassAgeGroupId = new Guid("a1371258-86d8-4ec2-9fbf-9b03a31cd548"),
                            PassPeriodId = new Guid("727c219a-0e3a-4eeb-9215-8602cbd62372"),
                            Price = 30m
                        },
                        new
                        {
                            Id = new Guid("362987f0-2fde-40e5-807a-86f969020505"),
                            IsDeleted = false,
                            Name = "Afternoon student pass",
                            PassAgeGroupId = new Guid("cae47722-1b8a-4578-b1c8-1f8b0412d7f1"),
                            PassPeriodId = new Guid("727c219a-0e3a-4eeb-9215-8602cbd62372"),
                            Price = 25m
                        });
                });

            modelBuilder.Entity("AlpineHub.Data.Models.PassAgeGroup", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasComment("Primary key of table");

                    b.Property<int>("MaxAge")
                        .HasColumnType("int")
                        .HasComment("Max age of client");

                    b.Property<int>("MinAge")
                        .HasColumnType("int")
                        .HasComment("Min age of client");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)")
                        .HasComment("Name of age group");

                    b.HasKey("Id");

                    b.ToTable("PassAgeGroups");

                    b.HasData(
                        new
                        {
                            Id = new Guid("a1371258-86d8-4ec2-9fbf-9b03a31cd548"),
                            MaxAge = 64,
                            MinAge = 18,
                            Name = "Adult"
                        },
                        new
                        {
                            Id = new Guid("cae47722-1b8a-4578-b1c8-1f8b0412d7f1"),
                            MaxAge = 26,
                            MinAge = 12,
                            Name = "Student"
                        },
                        new
                        {
                            Id = new Guid("3d8819ca-f1cf-48cd-c851-08dd19791faa"),
                            MaxAge = 12,
                            MinAge = 6,
                            Name = "Child"
                        });
                });

            modelBuilder.Entity("AlpineHub.Data.Models.PassPeriod", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasComment("Primary key of table PassPeriods");

                    b.Property<int>("DaysCount")
                        .HasColumnType("int")
                        .HasComment("Number of days for pass validity");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasComment("Name of pass period");

                    b.Property<TimeOnly>("ValidFromHour")
                        .HasColumnType("time")
                        .HasComment("Starting hour of pass period");

                    b.Property<TimeOnly>("ValidToHour")
                        .HasColumnType("time")
                        .HasComment("Ending hour of pass period");

                    b.HasKey("Id");

                    b.ToTable("PassPeriods");

                    b.HasData(
                        new
                        {
                            Id = new Guid("235024b0-64b9-4e2e-a0ee-48d0a2750953"),
                            DaysCount = 1,
                            Name = "Morning",
                            ValidFromHour = new TimeOnly(8, 30, 0),
                            ValidToHour = new TimeOnly(12, 30, 0)
                        },
                        new
                        {
                            Id = new Guid("727c219a-0e3a-4eeb-9215-8602cbd62372"),
                            DaysCount = 1,
                            Name = "Afternoon",
                            ValidFromHour = new TimeOnly(12, 30, 0),
                            ValidToHour = new TimeOnly(16, 30, 0)
                        },
                        new
                        {
                            Id = new Guid("a91d8261-2dd1-4631-a379-ce4cff155371"),
                            DaysCount = 1,
                            Name = "All day",
                            ValidFromHour = new TimeOnly(8, 30, 0),
                            ValidToHour = new TimeOnly(16, 30, 0)
                        });
                });

            modelBuilder.Entity("AlpineHub.Data.Models.ResortManager", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasComment("Primary key for ResortManager");

                    b.Property<Guid>("ApplicationUserId")
                        .HasColumnType("uniqueidentifier")
                        .HasComment("Foreign key for user relation(1-1)");

                    b.HasKey("Id");

                    b.HasIndex("ApplicationUserId");

                    b.ToTable("ResortManagers");
                });

            modelBuilder.Entity("AlpineHub.Data.Models.Slope", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Difficulty")
                        .HasColumnType("int")
                        .HasComment("Slope difficulty enum");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit")
                        .HasComment("Soft delete flag");

                    b.Property<bool>("IsOpen")
                        .HasColumnType("bit")
                        .HasComment("Flag indicating if slope is open");

                    b.Property<int>("Length")
                        .HasColumnType("int")
                        .HasComment("Length of the slope in meters");

                    b.Property<int>("LowerPointAltitude")
                        .HasColumnType("int")
                        .HasComment("Elevation at lowest point of the slope");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasComment("Name of the slope");

                    b.Property<int>("SlopeCondition")
                        .HasColumnType("int")
                        .HasComment("Slope condition enum");

                    b.Property<int>("UpperPointAltitude")
                        .HasColumnType("int")
                        .HasComment("Elevation at upmost point of the slope");

                    b.HasKey("Id");

                    b.ToTable("Slopes");

                    b.HasData(
                        new
                        {
                            Id = new Guid("6bbd6d8b-5f3a-4957-ab5d-a2c7136496c5"),
                            Difficulty = 3,
                            IsDeleted = false,
                            IsOpen = true,
                            Length = 2000,
                            LowerPointAltitude = 1300,
                            Name = "Wolf ride",
                            SlopeCondition = 0,
                            UpperPointAltitude = 2200
                        },
                        new
                        {
                            Id = new Guid("fc1cb7e9-3a97-43bb-a662-612cc5f62b83"),
                            Difficulty = 1,
                            IsDeleted = false,
                            IsOpen = true,
                            Length = 800,
                            LowerPointAltitude = 1800,
                            Name = "Rabbit's hole",
                            SlopeCondition = 0,
                            UpperPointAltitude = 2000
                        },
                        new
                        {
                            Id = new Guid("518d51dd-99d1-4c8a-8d1b-1da84e253bbf"),
                            Difficulty = 0,
                            IsDeleted = false,
                            IsOpen = true,
                            Length = 300,
                            LowerPointAltitude = 1350,
                            Name = "Lerner's paradise",
                            SlopeCondition = 1,
                            UpperPointAltitude = 1450
                        });
                });

            modelBuilder.Entity("AlpineHub.Data.Models.UserCart", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasComment("Primary key of table");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier")
                        .HasComment("Foreign key for user");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("UserCarts");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole<System.Guid>", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("AlpineHub.Data.Models.CartItem", b =>
                {
                    b.HasOne("AlpineHub.Data.Models.UserCart", "Cart")
                        .WithMany("CartItems")
                        .HasForeignKey("CartId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AlpineHub.Data.Models.Pass", "Pass")
                        .WithMany()
                        .HasForeignKey("PassId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cart");

                    b.Navigation("Pass");
                });

            modelBuilder.Entity("AlpineHub.Data.Models.Lift", b =>
                {
                    b.HasOne("AlpineHub.Data.Models.LiftType", "LiftType")
                        .WithMany("Lifts")
                        .HasForeignKey("LiftTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("LiftType");
                });

            modelBuilder.Entity("AlpineHub.Data.Models.Pass", b =>
                {
                    b.HasOne("AlpineHub.Data.Models.PassAgeGroup", "PassAgeGroup")
                        .WithMany("Passes")
                        .HasForeignKey("PassAgeGroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AlpineHub.Data.Models.PassPeriod", "PassPeriod")
                        .WithMany("Passes")
                        .HasForeignKey("PassPeriodId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PassAgeGroup");

                    b.Navigation("PassPeriod");
                });

            modelBuilder.Entity("AlpineHub.Data.Models.ResortManager", b =>
                {
                    b.HasOne("AlpineHub.Data.Models.ApplicationUser", "ApplicationUser")
                        .WithMany()
                        .HasForeignKey("ApplicationUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ApplicationUser");
                });

            modelBuilder.Entity("AlpineHub.Data.Models.UserCart", b =>
                {
                    b.HasOne("AlpineHub.Data.Models.ApplicationUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<System.Guid>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.HasOne("AlpineHub.Data.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.HasOne("AlpineHub.Data.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<System.Guid>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AlpineHub.Data.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.HasOne("AlpineHub.Data.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("AlpineHub.Data.Models.LiftType", b =>
                {
                    b.Navigation("Lifts");
                });

            modelBuilder.Entity("AlpineHub.Data.Models.PassAgeGroup", b =>
                {
                    b.Navigation("Passes");
                });

            modelBuilder.Entity("AlpineHub.Data.Models.PassPeriod", b =>
                {
                    b.Navigation("Passes");
                });

            modelBuilder.Entity("AlpineHub.Data.Models.UserCart", b =>
                {
                    b.Navigation("CartItems");
                });
#pragma warning restore 612, 618
        }
    }
}
